### ISSUE TITLE
dittoHeatmap on "scale.data" and rowSums == 0

### ISSUE THREAD

**Issue by christianwoe** [dtm2451/dittoSeq#127] opened 2023-09-14 07:25 UTC
Hi all,

I have a Seurat object with expression values averaged per sample/celltypes and generated a heatmap using the dittoheatmap function based on the _scale.data_ slot.

I recognized that some features were missing in the resulting figure and following warning:
```
Warning in .get_heatmap_data(object, genes, metas, assay, slot, cells.use) :
  Gene(s) or metadata removed due to absence of non-zero values within the 'cells.use' subset
```

I think might be because the R code tries to remove genes with zeros only by rowSums, which may be problematic if you have negative values alongside postive ones like in 'scale.data' that sum up into 0.

Here more details:
I found corresponding code in the _dittoHeatmap.R_ script where I find the following lines:
```
    if (any(rowSums(data)==0)) { 
        data <- data[rowSums(data)!=0,] 
        if (nrow(data)==0) { 
            stop("No target genes/metadata features have non-zero values in the 'cells.use' subset") 
        } 
        warning("Gene(s) or metadata removed due to absence of non-zero values within the 'cells.use' subset") 
    }  
```
Maybe I get it wrong, but as `if (any(rowSums(data)==0)) {` does not check if all expression values are zero, but only for the rowSums, it could cause problems in case you sum up negative and positive values that may end up in 0 as well. 
In my case I checked one of the missing genes and in scale.data all values were non-zero, but the rowsum was 0 and that may have caused this and the other genes to be removed as well as the warning.

Is this the expected behaviour?
I would assume a fix would be to make sure to check for non-zero entries rather than the rowsum.

However, I never observed this for a standard seurat object, but maybe the sum does not get exactly zero due to the high number of cells/values ending up in the calculations always resulting in a number slightly different from 0?

Many thanks & Kind regards,
Christian

**Comment by dtm2451** [comment] 2023-09-14 14:32
Hey there,

Thanks for this catch and for fishing out the relevant code!  You are definitely right.  This is not great and demands fixing.  Luckily, actually checking for presence of non-zero values should be a pretty easy fix!

As you've already  noted, the error message here does not match the if statement check.  Nowadays that's a red flag that I would have caught and I would have gone back to ensure the check matched the error exactly.  Always learning =).

To explain where this came from more than it being a mistake: `dittoHeatmap()` and `DoHeatmap()` are not completely equivalent, and the differences start all the way back at which data they target by default: `dittoHeatmap()` defaults to using the 'data' slot rather than the 'scale.data' slot whereas Seurat's `DoHeatmap()` uses the 'scale.data' slot by default.  `dittoHeatmap()` was designed around using the 'data' slot and then relying on re-scaling the data when wanted because of 2 problems I saw with defaulting to the 'scale.data' slot: 1. often not all genes are included for that slot (generally just the most highly variable features) so users would have to both understand this fact and know to change the `slot` input to access any left-out genes, and 2. the ability to regress out confounders in the generation of the 'scale.data' slot (`vars.to.regress` input of `Seurat::ScaleData()`) means the 'scale.data' is not necessarily a fully accurate picture.  Relative to other steps, re-scaling the 'data' matrix on-demand is not a super intensive step, so I've just never agreed with Seurat's defaulting behavior choice here.  (There's really also a third, but we are talking Seurat-world right now... 3. SingleCellExperiment pipelines tend not to retain the 'scale.data' equivalent, so in designing towards bridging the two worlds, I couldn't design towards that default-style anyway!)

With that said, although I recommend leaving `slot = 'data'`, the function is meant to be flexible to the use of 'scale.data'. There are just 2 things I want to point out for when doing this: 1. this data will already be scaled so you might as well also set `scale = 'none'`; and 2. the alternative output mode of setting `scaled.to.max = TRUE` is only built for the [0,inf] values of `slot` = 'data' or 'counts'/'raw.data'.

Thanks again & I'll reply again once changes are implemented,
Dan

**Comment by dtm2451** [comment] 2023-09-14 15:20
*Taking back my recommendation to not re-scale when using the 'scale.data' because I suspect Seurat actually does this, based on how plotting with Seruat's default coloring *without the re-scale* looks abnormally purple:

With `scale = 'none'`:
```
dittoHeatmap(pbmc_small, genes = VariableFeatures(pbmc_small), slot = 'scale.data', heatmap.colors = PurpleAndYellow(k = 50), scale = 'none')
```
![image](https://github.com/dtm2451/dittoSeq/assets/38870347/d3ca9c41-c98d-4c40-983a-b54d99340873)

With `scale = 'row'`, the default:
```
dittoHeatmap(pbmc_small, genes = VariableFeatures(pbmc_small), slot = 'scale.data', heatmap.colors = PurpleAndYellow(k = 50))
```
![image](https://github.com/dtm2451/dittoSeq/assets/38870347/8c6e8b37-8e90-42ba-a080-3a4f194bf223)

Also note: this is already making use of a fix from the `bug-heatmap-negative-values` branch that I'll push in as soon as I have time to test a bit more!
`if (any(rowSums(data*!=0*)==0)) {` 
`        data <- data[rowSums(data*!=0*)!=0,]`

In the meantime, **you can install with `remotes::install_github('dtm2451/dittoSeq@bug-heatmap-negative-values')` (then restart your R session if you'd already had dittoSeq loaded) to test with the fix yourself!**

**Comment by christianwoe** [comment] 2023-09-15 06:22
Dear Dan,

thank you for the quick fix.

I actually found that the results of `scale = 'none'` and `scale = 'row'` look basically identical once you use the breaks argument (which I usually apply to reduce effect of outliers).

```
breaks <- seq (-2,2, by = 0.1)
p <- dittoHeatmap(pbmc_small, genes = VariableFeatures(pbmc_small), slot = 'scale.data',
                  heatmap.colors = PurpleAndYellow(k = 50), scale = 'none', breaks = breaks)
print(p)

p <- dittoHeatmap(pbmc_small, genes = VariableFeatures(pbmc_small),
                  slot = 'scale.data', heatmap.colors = PurpleAndYellow(k = 50), scale = 'row', breaks = breaks)
print(p)
```

However, you convinced me to go for the 'data' slot instead.

Many thanks & Best wishes,
Christian

**Comment by dtm2451** [comment] 2023-10-05 22:04
Finally wrapped up this PR... and pushed the fix out to both the release and devel branches.  It'll ship in all the standard dittoSeq installation methods within a week =).

**Closed as completed by dtm2451** 2023-10-05 22:04 UTC
