### ISSUE TITLE
drop_levels is ignored in dittoHeatmap

### ISSUE THREAD

**Issue by RoganGrant** [dtm2451/dittoSeq#95] opened 2021-08-24 20:25 UTC
First of all, thank you for this lifesaver of a package. I could make this plot manually, but it was getting to be a real pain.

Minor issue, but pheatmap seems to ignore the `drop_levels` parameter (TRUE by default) even if I specify manually, e.g.

```
dittoHeatmap(object = miniseq, 
                         genes = markers, 
                         annot.by = "type_state", 
                         scaled.to.max = T,
                         complex = F,
                         drop_levels = T)
```

However if I manually refactor first `miniseq$group = factor(as.character(miniseq$group))`, the unused level disappears. Is `drop_levels` set to FALSE within the wrapper somewhere? FWIW, other parameters passed to pheatmap work just fine, e.g. `labels_row`.

**Comment by dtm2451** [comment] 2021-09-02 17:43
Sorry for the delay!
I've just looked into this and can confirm that dittoSeq never touches the `drop_levels` input.  BUT it does put together it's own annotation bar color mappings via the `annotation_colors` input, and it seems the issue is that if `annotation_colors` contains a color for all levels, then `drop_levels` won't override that.  (Same effect occurs for both pheatmap and ComplexHeatmap outputs.)

It seems to me that the best solution I can offer, to keep dittoSeq maximally accessible to all users, will be to implement my own version of the `drop_levels` infrastructure so that dropped levels don't receive a color.  I'll work on that!

Example:
```
library(dittoSeq)
# Make data
example(importDittoBulk, echo = FALSE)
genes <- getGenes(myRNA)[1:30]
myRNA$clustering <- as.factor(myRNA$clustering)

# Run dittoHeatmap with data.out = TRUE for testing
with_ann_colors <- dittoHeatmap(myRNA, genes,
    annot.by = "clustering",
    cells.use = myRNA$clustering!="3",
    drop_levels = TRUE,
    data.out = TRUE)

# Check that we have a proper setup
head(with_ann_colors$annotation_col$clustering)
table(with_ann_colors$annotation_col$clustering)

# Remove annotation colors from a duplicated set of the inputs
no_ann_colors <- with_ann_colors
no_ann_colors$annotation_colors <- NULL

# Test with pheatmap::pheatmap
do.call(pheatmap::pheatmap, with_ann_colors)
do.call(pheatmap::pheatmap, no_ann_colors)

# Test with ComplexHeatmap::pheatmap (equivalent of running dittoHeatmap with `complex=TRUE`)
do.call(ComplexHeatmap::pheatmap, with_ann_colors)
do.call(ComplexHeatmap::pheatmap, no_ann_colors)
```

**Comment by RoganGrant** [comment] 2021-09-02 18:39
Thank you, and no worries at all! For now this is probably low priority given that simply manually dropping solves the issue, but I really appreciate you working on a solution.

**Comment by dtm2451** [comment] 2021-09-02 18:39
That wasn't too hard =p.

But it may be a bit before this gets pushed through to the devel version of the package... there seems to be another issue currently where ComplexHeatmap tests are failing so I'm not sure how soon I'll be able to push this through.

In the meantime, you can install the fix from github with `BiocManager::install("dtm2451/dittoSeq@dittoHeatmap-drop_levels")`

**Comment by dtm2451** [comment] 2021-09-10 22:12
The fix for this is now pushed through in both release and devel!

**Closed by dtm2451** 2021-09-10 22:12 UTC
